version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: masajes_db
      POSTGRES_USER: masajes_user
      POSTGRES_PASSWORD: masajes_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U masajes_user -d masajes_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://masajes_user:masajes_password@postgres:5432/masajes_db
      - NEXTAUTH_SECRET=your-secret-key
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: